site_name: ğ—¥ğ—§ğ—¨ ğ—¦ğ—˜ğ—¥ğ—©ğ—˜ğ—¥
theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  logo: assets/favicon.png
  icon:
    logo: logo
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: indigo
    toggle:
      icon: material/weather-night
      name: ë‹¤í¬ ëª¨ë“œë¡œ ì „í™˜
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: indigo
    toggle:
      icon: material/weather-sunny
      name: í™”ì´íŠ¸ ëª¨ë“œë¡œ ì „í™˜
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/IPECTER
      name: ê¹ƒí—ˆë¸Œ
    - icon: fontawesome/brands/twitch
      link: https://twitch.tv/ipecter
      name: "íŠ¸ìœ„ì¹˜: ì´íŒ©í„°"
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/c/ì´íŒ©í„°
      name: "ìœ íŠœë¸Œ: ì´íŒ©í„°"
    - icon: fontawesome/brands/twitch
      link: https://twitch.tv/rtuserver
      name: "íŠ¸ìœ„ì¹˜: RTU ì„œë²„"
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@rtuserver
      name: "ìœ íŠœë¸Œ: RTU ì„œë²„"
    - icon: fontawesome/brands/github
      link: https://github.com/IPECTER
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/rtuserver
      name: "íŠ¸ìœ„í„°"